#!/usr/bin/bash

check_os() {
    : '
        Compat for Windows & Linux & MacOS.
    '

    if [ "$_OS_ACCEPT" != 1 ]; then
        OS_TYPE=$(uname)

        if [[ "$OS_TYPE" == "Linux" ]]; then
            cat /etc/os-release &>/dev/null
            _OS_GNU_LINUX=1
            _OS_PAWNCC="pawncc"
            _OS_DISABLE_GNU_NANO="false"
            _OS_SSERVER="samp03svr"
        elif [[ "$OS_TYPE" == "Darwin" ]]; then
            _OS_DARWIN=1
            _OS_PAWNCC="pawncc"
            _OS_DISABLE_GNU_NANO="true"
            _OS_SSERVER="samp03svr"

            if ! command -v docker &>/dev/null; then
                echo -e "$(bash_coltext_r "crit:") Docker not found!.."
                echo "Install first!. See: https://github.com/vilksons/triops/wiki/Get-Started"
            fi
        elif [ -d "/c/Windows/System32" ] || [ -d "/mnt/c/Windows/System32" ] || [ -d "/Windows/System32" ]; then
            _OS_WINDOWS=1
            _OS_PAWNCC="pawncc.exe"
            _OS_DISABLE_GNU_NANO="true"
            _OS_SSERVER="samp-server.exe"
        fi

        if { [ "$_OS_WINDOWS" == 1 ] && [ "$_OS_GNU_LINUX" == 1 ]; } || 
           [ "$_OS_DARWIN" == 1 ] || 
           { [ "$_OS_GNU_LINUX" == 1 ] && [ "$_OS_DARWIN" == 1 ]; }; then
            
            echo -e "$(bash_coltext_a ":: System detected both Windows and Linux / MacOS (Darwin). Which one will you choose?")"
            read -r -p "Choose OS for Triops Y) Windows, B) GNU/Linux, X) Darwin (Mac): " PERMISSION_NEED_OS

            while true; do
                case "$PERMISSION_NEED_OS" in
                    [Yy]) 
                        _OS_PAWNCC="pawncc.exe"
                        _OS_DISABLE_GNU_NANO="true"
                        _OS_SSERVER="samp-server.exe"
                        _OS_WINDOWS=1
                        _OS_GNU_LINUX=0
                        _OS_DARWIN=0
                        break 
                        ;;
                    [Bb]) 
                        _OS_PAWNCC="pawncc"
                        _OS_DISABLE_GNU_NANO="false"
                        _OS_SSERVER="samp03svr"
                        _OS_WINDOWS=0
                        _OS_GNU_LINUX=1
                        _OS_DARWIN=0
                        break 
                        ;;
                    [Xx]) 
                        _OS_PAWNCC="pawncc"
                        _OS_DISABLE_GNU_NANO="false"
                        _OS_SSERVER="samp03svr"
                        _OS_WINDOWS=0
                        _OS_GNU_LINUX=0
                        _OS_DARWIN=1
                        break 
                        ;;
                    *) 
                        echo -e "$(bash_coltext_r "err:") Invalid selection. Please enter the correct option!"
                        read -r -p "Choose OS for Triops Y) Windows, B) GNU/Linux, X) Darwin (Mac): " PERMISSION_NEED_OS 
                        ;;
                esac
            done
        fi
    fi
}
